language: ruby
rvm:
- 2.3.0
- 2.2.4
- 2.1.8
- 2.0.0
before_install:
- gem install bundler
- bundle --version
deploy:
  provider: rubygems
  api_key:
    secure: d2sBTznIo/xcoSPAvPCGrizeQlvVQOh2Vma6GK/vZrM4EiOjzQTe8UB21WiOHjoPejI1+wi1V+Vf4Ule4K01xzQDrL6DdcdNSplmrS73GPYDEcYJMQcRUkup1WNpUsO0z1gpiw6eKDVObyxtnFjH1cwU4mDkip9NiPhrGbig5rEn0EUJkQxWn3QHHp/IfwOBagIjLecFTP27A/diWsdlkIzBt9TS1HsKUx7dF7ktJQIgbgXCgD4Rr2PfrelsPA6e5vrSvxo8ORr6j978N8ZPpDSZtBQbDR7i4KA8WYr4cprDa6PEhGMMvTb1b7mBoXnbfTPCgJcWVB0/Y9A4qlV9pcU+nEb9hN6E8CcvtgvmBYDD4PUAj0gE8nGg9eO84VrII7KaZRJkGXITR9kpNaglZrwyncOZ3tt8AV7Ee46VEpSGNlWXZdFRm4i1QKnE0iExPB1UOiLjpFjspljTzCHV4tt5s+eEthTx4Lqw3iqBqpcn/bpVOXypCxSkr0AfM2xSGFG27ItDy0i2K+evOKlIlRu0AFGhhHlBpkccOxW9I7SmY2LW9jrvSV8HBp6msrnncQOfGaA61bgQy9o8qKTDGeJ4p3MyhOSV7aSHFNSdo9/7f26G+jH/CZnk8lsN5RfY1X8v3kJxZX7eB+lcaV/oyHr5Q95+vkBuW92oHb6uxec=
  gem: mcblocky
  on:
    repo: DeltaWhy/mcblocky
